- class_name: 近期计划
  project_list:
    - content: 工作项目顺利收尾完工
      state: true
    - content: 返深
      state: true
    - content: 抽空处理分享describe
      state: true
    - content: 考虑转行
      state: false

- class_name: 要处理的项目
  project_list:
    - content: 做一款阅读类博客主题
      state: false
    - content: 导航页
      state: false
    - content: 个人主页
      state: false
    - content: 简历页
      state: false
    - content: 重构 iCat 布柒糖FM
      state: true
    - content: 重构 iCat 卡布奇诺
      state: true
    - content: 二次重构优化 iCat爱吃肉的猫 V2.0
      state: true
    - content: 布柒糖FM 项目铺展
      state: false

- class_name: 自我提升
  project_list:
    - content: 每月至少阅读一本书
      state: true
    - content: 养成定点喝水的习惯
      state: true
    - content: 每日刮胡子
      state: true
    - content: 定期护肤
      state: false
    - content: 专升本
      state: false
    - content: 坚持健身
      state: false

- class_name: 想学的技术
  project_list:
    - content: CSS进阶
      state: true
    - content: Javascript进阶
      state: false
    - content: 微信小程序
      state: true
    - content: 单片机
      state: false
    - content: Node
      state: true
    - content: Docker
      state: true
    - content: Webpack
      state: false
    - content: Photoshop
      state: true
    - content: Illustrator
      state: false
    - content: EJS
      state: true

- class_name: 想买的东西
  project_list:
    - content: 奥林巴斯 EM-5 III
      state: false
    - content: SONY A7R3A
      state: false
    - content: DJI Mini 3 Pro
      state: false
    - content: MacBook Pro
      state: true
    - content: Apple Watch Series 7
      state: true
    - content: 换WD 移动硬盘 2TB
      state: false
